### ISSUE TITLE
Use types instead of identifiers for make expressions

### ISSUE THREAD

**Issue by mr-cheffy** [ReCT-Lang/nrc#3]
https://github.com/ReCT-Lang/nrc/blob/main/src%2Fparser%2Fnodes.json#L74-L77

Using actual type references here will cover more occasions than just an identifier, for example, if the type has generics or if it's inside a namespace

**Comment by Khhs167** [comment]
Identifiers may have generics namespaces and so on and so forth. An identifier is just anything which identifies anything, such as `package_name::SomeGenericType[void]` or `string`
